spring:
  application:
    name: product-service  # unique service name

  cloud:
    stream:
      bindings:
        category-out-0:
          destination: category-topic
          content-type: application/json

        product-out-0:
          destination: product-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

  instance:
    prefer-ip-address: true